# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 

(**hint**: np.zeros)

In [3]:
nullVector = np.zeros(10)
print(nullVector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.size(arr))
print(arr.itemsize)

8
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
vector = np.zeros(10)
print(vector)
vector[4] = 11
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.70352752 0.14067557 0.13496018]
  [0.50481832 0.22385223 0.87399778]
  [0.53355715 0.94051854 0.77733861]]

 [[0.24304421 0.99947969 0.43902665]
  [0.06518249 0.38435714 0.09498567]
  [0.79318368 0.18503801 0.54442316]]

 [[0.33272526 0.75836562 0.8650766 ]
  [0.39002212 0.37850314 0.44557016]
  [0.46279221 0.9757823  0.44152914]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
arr = np.random.random((10,10))
print(arr)
print(arr.max(),arr.min())

[[0.98707519 0.03309251 0.03658401 0.16631544 0.85988672 0.37726142
  0.6593004  0.86259758 0.30501918 0.86088486]
 [0.20136514 0.01448316 0.06520799 0.33746747 0.40078119 0.46179664
  0.24847395 0.37262229 0.75822255 0.88053435]
 [0.6884969  0.95608381 0.67930422 0.77460374 0.85167642 0.94580819
  0.41366766 0.15590114 0.04792579 0.53453195]
 [0.041766   0.09634706 0.30674474 0.41993578 0.24199949 0.75637388
  0.72332783 0.44626501 0.26505957 0.06503404]
 [0.39675573 0.93038732 0.85553227 0.29359565 0.30205745 0.68975445
  0.98682983 0.37181788 0.11263729 0.66903805]
 [0.25530239 0.39367623 0.72316189 0.18408327 0.99965677 0.03629728
  0.9644506  0.4779896  0.29594201 0.1966142 ]
 [0.35721977 0.95665173 0.25479773 0.19115963 0.95365199 0.61297039
  0.00631972 0.81149452 0.16805651 0.80041893]
 [0.09049988 0.26676968 0.3050155  0.02281858 0.6340002  0.40047258
  0.76543429 0.54182758 0.90968614 0.86979646]
 [0.90386345 0.91858899 0.56233878 0.37742864 0.99395377 0.81321894
  0.8499486 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
arr = np.random.random(30)
print(arr)
print(np.mean(arr))

[0.70786568 0.71657073 0.2573814  0.59454171 0.65700185 0.52307485
 0.09357172 0.71858996 0.48470099 0.71858919 0.82418615 0.16405178
 0.11609376 0.77924256 0.81222646 0.30882867 0.86449806 0.14554727
 0.0106411  0.90001979 0.9217689  0.29341223 0.62716268 0.18658737
 0.90549717 0.11710854 0.9078049  0.09572277 0.84912695 0.47121507]
0.5257543414934822


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
x = np.ones((4,4))
print(x)
print("New Array with 1 on the border and O inside")
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
New Array with 1 on the border and O inside
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print("0 * np.nan :",0*np.nan)
print("np.nan == np.nan :",np.nan == np.nan)
print("np.inf > np.nan :",np.inf > np.nan)
print("np.nan-np.nan :",np.nan-np.nan)
print("0.3 == 3 * 0.1 :",0.3 == 3 * 0.1)

0 * np.nan : nan
np.nan == np.nan : False
np.inf > np.nan : False
np.nan-np.nan : nan
0.3 == 3 * 0.1 : False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
# Creating CheckerBoard Pattern
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
array= np.array([[0,1], [1,0]])
arr = np.tile(array,(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
arr = np.random.random((5,5))
arrmax, arrmin = arr.max(), arr.min()
Z=(arr-arrmin)/(arrmax-arrmin)
print(Z)

[[0.92301891 0.10325946 0.99980953 0.48762778 0.        ]
 [0.21377077 0.09040852 0.271117   0.82094544 0.53110166]
 [0.34163727 0.64932115 0.99723434 0.23459817 0.6923663 ]
 [0.80811336 0.39912767 0.91362734 1.         0.65737596]
 [0.9119221  0.68986075 0.02872653 0.28609938 0.16106683]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
#print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
#Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z
# The commented ones are not legal

array([ 0.,  1.,  2.,  3., -4., -5., -6., -7., -8.,  9., 10.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-5. -6.  7. -4. -8. -1. -1. -8.  1.  4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[0 2 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [31]:
defaults = np.seterr(all="ignore")
arr = np.ones(1) / 0
arr

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
today     = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(today,yesterday,tomorrow)

2022-03-25 2022-03-24 2022-03-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [34]:
arr = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [36]:
Z = np.random.uniform(0,10,10)
# 5 techniques are:
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[4. 7. 9. 8. 2. 3. 5. 9. 9. 3.]
[4. 7. 9. 8. 2. 3. 5. 9. 9. 3.]
[4. 7. 9. 8. 2. 3. 5. 9. 9. 3.]
[4 7 9 8 2 3 5 9 9 3]
[4. 7. 9. 8. 2. 3. 5. 9. 9. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [37]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [38]:
def generate():
  for x in range(10):
    yield x
arr = np.fromiter(generate(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [39]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [40]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.18811444 0.19419938 0.19522198 0.54990214 0.565201   0.64649343
 0.68074172 0.76382271 0.82967006 0.84160802]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [41]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 0 1 0]
[1 0 1 1 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [43]:
Z = np.zeros(5)
Z.flags.writeable = False
# Check if the array 'Z' is immutable
try:
  Z[0] = 1
except:
  print("Cannot update/add new elements into an immutable array")

Cannot update/add new elements into an immutable array


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [44]:
arr = np.random.random((10,2))
x,y = arr[:,0],arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.73428242 0.84319174 0.89449222 0.95156607 0.85037044 0.62592229
 0.24982    0.23666982 0.13557659 0.56994993]
[1.18142256 0.02136085 0.23506842 0.53196711 0.08831274 1.51860398
 0.1727315  0.8430032  1.39279051 0.95356734]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [45]:
arr = np.random.random(10)
print("Original Array :",arr)
print()
arr[arr.argmax()] = 0
print("New Array :",arr)

Original Array : [0.92354421 0.35138203 0.60053901 0.26300643 0.69167723 0.37257444
 0.79435706 0.14102255 0.45862746 0.67081193]

New Array : [0.         0.35138203 0.60053901 0.26300643 0.69167723 0.37257444
 0.79435706 0.14102255 0.45862746 0.67081193]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [46]:
Z = np.zeros((4,4), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,4),np.linspace(0,1,4))
print(Z)

[[(0.        , 0.        ) (0.33333333, 0.        )
  (0.66666667, 0.        ) (1.        , 0.        )]
 [(0.        , 0.33333333) (0.33333333, 0.33333333)
  (0.66666667, 0.33333333) (1.        , 0.33333333)]
 [(0.        , 0.66666667) (0.33333333, 0.66666667)
  (0.66666667, 0.66666667) (1.        , 0.66666667)]
 [(0.        , 1.        ) (0.33333333, 1.        )
  (0.66666667, 1.        ) (1.        , 1.        )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [47]:
X = np.arange(10)
#print(X)
Y = X + 0.5
#print(Y)
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480236


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [49]:
np.set_printoptions()
arr = np.random.random(15).reshape(3,5)
print(arr)

[[0.93821845 0.73113162 0.39466936 0.04655192 0.09044674]
 [0.30703144 0.7217666  0.78260309 0.35021516 0.64300465]
 [0.52189921 0.3305876  0.4751113  0.55092824 0.96227584]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [50]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])

61


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [51]:
arr = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                   ('color',    [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [52]:
arr = np.random.random((10,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.9054336  0.66428898 0.3565103  0.41900354 0.31377909
  0.45246047 0.23617723 0.13154175 0.07236962]
 [0.9054336  0.         0.31999941 0.89010157 1.04179831 0.95152559
  0.45438159 0.67303738 0.87036168 0.85025386]
 [0.66428898 0.31999941 0.         0.76333795 0.91047452 0.64702859
  0.27731804 0.43064675 0.6682873  0.62493868]
 [0.3565103  0.89010157 0.76333795 0.         0.15209407 0.66445963
  0.48701384 0.41004504 0.2259825  0.30216864]
 [0.41900354 1.04179831 0.91047452 0.15209407 0.         0.73195243
  0.63573106 0.5335905  0.30670572 0.38556627]
 [0.31377909 0.95152559 0.64702859 0.66445963 0.73195243 0.
  0.55911279 0.35799564 0.43922969 0.36242476]
 [0.45246047 0.45438159 0.27731804 0.48701384 0.63573106 0.55911279
  0.         0.226885   0.41958605 0.39587474]
 [0.23617723 0.67303738 0.43064675 0.41004504 0.5335905  0.35799564
  0.226885   0.         0.24812426 0.19490456]
 [0.13154175 0.87036168 0.6682873  0.2259825  0.30670572 0.43922969
  0.41958605 0.24812

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [53]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
filedata = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

arr = np.genfromtxt(filedata, delimiter=",", dtype=np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [55]:
arr = np.arange(6).reshape(2,3)
for index, value in np.ndenumerate(arr):
    print(index, value)

for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [56]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [57]:
ndim = 10
x = 3
Z = np.zeros((ndim,ndim))
np.put(Z, np.random.choice(range(ndim*ndim), x, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [58]:
x = np.random.rand(5,5)
arr = x - x.mean(axis=1, keepdims=True)
print(arr)

[[-0.22281416  0.07915782 -0.20505054  0.25971764  0.08898924]
 [-0.35302091 -0.28284849  0.47514416 -0.14834931  0.30907455]
 [ 0.24366875 -0.03463473  0.0218776  -0.32200823  0.09109661]
 [ 0.14162995  0.06425331 -0.00495447 -0.14107128 -0.05985751]
 [ 0.22067664  0.00269516 -0.31247323  0.21217454 -0.1230731 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [59]:
arr = np.random.randint(0,10,(3,3))
print(arr)
n = 1
print(arr[arr[:,n].argsort()])

[[5 0 9]
 [3 4 7]
 [0 2 8]]
[[5 0 9]
 [0 2 8]
 [3 4 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [60]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 2 2 1 1 0 2 1 1 1]
 [0 2 0 1 1 2 2 2 2 2]
 [2 1 1 2 2 1 1 2 0 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [61]:
arr = np.random.uniform(0,1,10)
num = 0.5
m = arr.flat[np.abs(arr - num).argmin()]
print(m)

0.3746869113264144


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [63]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', "no name")

arr = NamedArray(np.arange(5), "range5array")
print (arr.name)

range5array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [64]:
arr = np.ones(10)
I = np.random.randint(0,len(arr),20)
arr += np.bincount(I, minlength=len(arr))
print(arr)

np.add.at(arr, I, 1)
print(arr)

[4. 2. 6. 5. 1. 2. 3. 1. 4. 2.]
[ 7.  3. 11.  9.  1.  3.  5.  1.  7.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [65]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
newx = np.bincount(i,x)
print(newx)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [66]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [67]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 59 66 51]
 [58 46 59 60]
 [53 64 66 44]]
[[47 59 66 51]
 [58 46 59 60]
 [53 64 66 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [68]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())

[0.50236137 0.62659205 0.23834811 0.6452868  0.34712493 0.4555686
 0.5064702  0.34096601 0.40348543 0.51646466]
0    0.502361
1    0.626592
2    0.238348
3    0.645287
4    0.347125
5    0.455569
6    0.506470
7    0.340966
8    0.403485
9    0.516465
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.3816301 , 1.26745919, 2.56960756, 1.47010757, 1.46688557])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [70]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [71]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [72]:
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [73]:
arr = np.random.randint(0,100,(10,3))
F = np.roll(arr.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 74) ( 4, 99) ( 5, 67) ( 5, 98) ( 6, 57) ( 6, 70) ( 7, 27) ( 7, 87)
 (17, 72) (17, 91) (18, 63) (18, 71) (24, 57) (24, 99) (27, 79) (27, 87)
 (27, 89) (36, 38) (36, 75) (38, 75) (57, 70) (57, 99) (63, 71) (67, 98)
 (72, 91) (74, 99) (76, 89) (79, 89) (89, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [74]:
c = np.bincount([1,1,2,3,4,4,6])
arr = np.repeat(np.arange(len(c)),c)
print(arr)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [75]:
def movingAverage(arr, n=3) :
  ret = np.cumsum(arr, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n

arr = np.arange(20)
print(movingAverage(arr,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [76]:
from numpy.lib import stride_tricks

def rollingWindow(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

arr = rollingWindow(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [77]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([ 0.52905393,  0.42107284, -0.76354934, -0.80901708,  0.49592295,
        0.63933991,  0.1567618 ,  0.18375471, -0.5233234 ,  0.8207532 ,
        0.03761326,  0.18632874,  0.8628112 , -0.85651411,  0.52529165,
        0.71437317, -0.63889336,  0.22896607, -0.7367397 , -0.18123019,
       -0.16182971,  0.04459591,  0.12628384, -0.33238553,  0.24885403,
       -0.98951851, -0.98680189, -0.97383328,  0.62780719, -0.78241694,
        0.31700783,  0.05548603,  0.39883439, -0.58077717, -0.45265749,
       -0.65179339,  0.18014697,  0.48771865, -0.66361022,  0.20631877,
        0.62704901, -0.13526876, -0.26951389,  0.93486069,  0.54977074,
        0.48848836,  0.43214725, -0.34685544,  0.4045689 , -0.9292982 ,
        0.79160395,  0.81702837, -0.34810745, -0.06492704, -0.2630089 ,
        0.98839121, -0.37075999,  0.79620989,  0.08467032,  0.72446044,
       -0.73443998,  0.778809  , -0.70855879,  0.86643965,  0.41453897,
       -0.30422962, -0.43050805,  0.56878721,  0.02149214,  0.88

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [78]:
def distanceCalculation(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distanceCalculation(p0, p1, p))

[12.80831916 16.47140697  6.30912417  3.63168865  1.00476143  0.4696029
  4.08217895  2.76483177  7.47914434  1.78310221]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [79]:
p0 = np.random.uniform(-10, 10, (10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distanceCalculation(p0,p1,p_i) for p_i in p]))

[[ 5.59104279  4.08569467  7.20317905  3.45461463  0.82715371  3.62893517
   0.49655403  6.21970537  2.16972118  2.85611359]
 [ 2.3945265   2.15801042  0.12906437  6.05558012  7.94729349  9.59001537
   6.97362401  2.61368973  7.60625263  0.72126671]
 [ 3.71903464  4.04159342  4.89542422  0.75221623  2.41447024  4.85232191
   1.2042446   4.05005421  0.54323207  2.3424779 ]
 [ 3.54232466 10.50671013  4.66480974  7.00630171  1.26639755  2.20693267
   0.56540967  2.27641018  7.48177804  7.44962602]
 [ 2.33183443 14.71985511 12.28251797 13.67345469  1.44180881  1.18780771
   1.14106579  0.15517152 13.6174782  10.49784926]
 [13.23246539 12.16333346  5.21821205  5.32554988  7.236647    4.73529447
   8.41498772 13.16086994  5.08596907 11.2466792 ]
 [ 2.06255976  3.00743352 12.9766312   6.49154102  5.22542382  8.92648899
   3.57542067  3.83017173  4.29716557  3.69857844]
 [ 0.45031495 10.18621352  8.11890395 11.18263026  3.937866    4.33330015
   3.40523301  1.24716111 11.70696808  6.40388434]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [80]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 2 5 4 1 4 3 9 7 7]
 [1 7 3 9 2 2 5 8 7 6]
 [8 1 9 5 7 2 3 1 7 3]
 [8 8 9 5 2 8 3 5 6 9]
 [3 8 1 1 1 9 0 7 0 5]
 [5 0 7 2 8 2 4 8 0 6]
 [7 5 1 0 6 8 5 6 8 9]
 [4 3 0 2 9 9 8 2 0 6]
 [0 5 5 3 4 5 7 8 3 1]
 [8 8 5 3 9 2 4 9 1 5]]
[[0 0 0 0 0]
 [0 4 2 5 4]
 [0 1 7 3 9]
 [0 8 1 9 5]
 [0 8 8 9 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [81]:
arr = np.arange(1,15,dtype=np.uint32)
newarr = stride_tricks.as_strided(arr,(11,4),(4,4))
print(newarr)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [82]:
arr = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(arr)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [83]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [84]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 0]
   [2 4 1]
   [2 4 2]]

  [[0 0 3]
   [4 1 1]
   [4 2 1]]

  [[0 3 1]
   [1 1 0]
   [2 1 4]]

  [[3 1 0]
   [1 0 0]
   [1 4 2]]

  [[1 0 3]
   [0 0 3]
   [4 2 2]]

  [[0 3 1]
   [0 3 0]
   [2 2 0]]

  [[3 1 2]
   [3 0 4]
   [2 0 0]]

  [[1 2 1]
   [0 4 2]
   [0 0 1]]]


 [[[2 4 1]
   [2 4 2]
   [0 1 3]]

  [[4 1 1]
   [4 2 1]
   [1 3 2]]

  [[1 1 0]
   [2 1 4]
   [3 2 3]]

  [[1 0 0]
   [1 4 2]
   [2 3 4]]

  [[0 0 3]
   [4 2 2]
   [3 4 2]]

  [[0 3 0]
   [2 2 0]
   [4 2 1]]

  [[3 0 4]
   [2 0 0]
   [2 1 3]]

  [[0 4 2]
   [0 0 1]
   [1 3 3]]]


 [[[2 4 2]
   [0 1 3]
   [2 0 3]]

  [[4 2 1]
   [1 3 2]
   [0 3 3]]

  [[2 1 4]
   [3 2 3]
   [3 3 3]]

  [[1 4 2]
   [2 3 4]
   [3 3 3]]

  [[4 2 2]
   [3 4 2]
   [3 3 2]]

  [[2 2 0]
   [4 2 1]
   [3 2 0]]

  [[2 0 0]
   [2 1 3]
   [2 0 1]]

  [[0 0 1]
   [1 3 3]
   [0 1 0]]]


 [[[0 1 3]
   [2 0 3]
   [3 1 4]]

  [[1 3 2]
   [0 3 3]
   [1 4 3]]

  [[3 2 3]
   [3 3 3]
   [4 3 2]]

  [[2 3 4]
   [3 3 3]
   [3 2 3]]

  [[3 4 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [85]:
class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i,j = index
    super(Symetric, self).__setitem__((i,j), value)
    super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  9 14 10 16]
 [ 9  9 12  4  9]
 [14 12  5 42  5]
 [10  4 42  4 10]
 [16  9  5 10  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [86]:
p = 10
n = 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [87]:
arr = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], k), axis=0),
                                       np.arange(0, arr.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [88]:
Z = np.arange(1000)
np.random.shuffle(Z)
n = 4
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[996 997 998 999]
[999 998 997 996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [89]:
def cartesianProduct(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
  return ix

print(cartesianProduct(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [90]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [91]:
num = 5e-7
num = 10
x = np.random.rand(num)
try:
  %timeit np.power(int(x),3)
  %timeit x*x*x
  %timeit np.einsum('i,i,i->i',x,x,x)
except:
  print("Error: Only accepts integer values")

Error: Only accepts integer values


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [92]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [93]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 4 2]
 [3 3 3]
 [0 3 0]
 [0 0 3]
 [0 2 1]
 [3 2 0]
 [4 1 1]
 [3 0 0]
 [1 2 0]
 [4 2 3]]
[[3 4 2]
 [0 3 0]
 [0 0 3]
 [0 2 1]
 [3 2 0]
 [4 1 1]
 [3 0 0]
 [1 2 0]
 [4 2 3]]
[[3 4 2]
 [0 3 0]
 [0 0 3]
 [0 2 1]
 [3 2 0]
 [4 1 1]
 [3 0 0]
 [1 2 0]
 [4 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [94]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [95]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [96]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)      
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B) 

array([[0.07086192, 0.10825835, 0.01552354, 0.1449746 , 0.07772447,
        0.06184554, 0.05352744, 0.07588112, 0.06336706, 0.11316299],
       [0.34723971, 0.53049079, 0.07606889, 0.71040885, 0.38086777,
        0.30305736, 0.26229677, 0.37183493, 0.31051317, 0.55452467],
       [0.14556584, 0.22238625, 0.03188873, 0.29780943, 0.15966301,
        0.12704422, 0.10995704, 0.15587636, 0.13016976, 0.23246146],
       [0.35904851, 0.54853152, 0.07865582, 0.73456817, 0.39382018,
        0.31336362, 0.27121686, 0.38448016, 0.32107299, 0.57338274],
       [0.28227411, 0.43124047, 0.06183705, 0.57749739, 0.30961064,
        0.2463579 , 0.21322327, 0.30226777, 0.25241879, 0.45077781],
       [0.32811783, 0.50127759, 0.07187991, 0.67128788, 0.35989404,
        0.28636852, 0.24785255, 0.35135863, 0.29341376, 0.52398797],
       [0.0417796 , 0.06382821, 0.00915255, 0.08547581, 0.0458257 ,
        0.03646361, 0.03155933, 0.04473887, 0.03736069, 0.06671995],
       [0.3223516 , 0.49246831, 0.0706167

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [97]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [98]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [99]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.01251295 0.32826117]


Reference: https://www.kaggle.com/code/utsav15/100-numpy-exercises/notebook